name: CI-CD GitOps

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gitopsfc:${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/gitopsfc:latest

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update Kubernetes resources
        run: |
          cd k8s
          kustomize edit set image goserver=${{ secrets.DOCKERHUB_USERNAME }}/gitopsfc:${{ github.run_number }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || git commit -am "Bump docker version"

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref }}
